Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,4 +14,4 @@ jobs:
         
         
       - name: Greeting
-        run: echo "Simulating an error!"
+        run: echo "Simulating an error!"; exit 1
